# Generated by Django 3.2.16 on 2022-12-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date1',
            field=models.DateField(default=1986),
            preserve_default=False,
        ),
    ]
